name: Flutter CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter actions
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows application
      run: flutter build windows

    - name: Tag with version
      id: tag_version
      run: |
        echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.POS_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: build/windows/runner/Release/
